namespace LPG2.Runtime
{

    /**
 * Low-Level interface to act as recipient for error messages generated by a 
 * parser/compiler.
 */
    public interface IMessageHandler
    {
        /**
     * 
     * When a location is undefined, the value of its offset is 0.
     * 
     * @param errorCode
     * @param msgLocation
     * @param errorLocation
     * @param filename
     * @param errorInfo
     */
        void handleMessage(int errorCode, int[] msgLocation, int[] errorLocation, string filename, 
            string[] errorInfo);
    }

    /**
     * Indexes into the 6-int location arrays produced by LexStream.getLocation.
     * Kept as a static class (not interface fields) for netstandard2.0.
     */
    public static class MessageHandlerLocation
    {
        public const int OFFSET_INDEX = 0;
        public const int LENGTH_INDEX = 1;
        public const int START_LINE_INDEX = 2;
        public const int START_COLUMN_INDEX = 3;
        public const int END_LINE_INDEX = 4;
        public const int END_COLUMN_INDEX = 5;
    }
}
